/**************************************************
*WightDanielUnit5.java
*Daniel Wight
*
*Program generating random numbers and statistics about them
*************************************************************/

import java.util.Scanner;
import java.util.Random;

public class WightDanielUnit5
{
	public static void main(String[] args)
	{
		Scanner stdIn = new Scanner(System.in);
		Random random = new Random();

		final String HEADING_FMT_STR = "%1s%9s%15s%15s%15s%18s\n";  //sets the heading positions
		final String DATA_FMT_STR = "%5d%9d%15d%15d%15.0f%18.2f\n";  //sets the data positions

		String randmaxString;  //text entered for max random number
		String roundsString;  //text entered for max number of rounds
		int randmax;  //integer parsed from max random number text
		int rounds;  //integer parsed from max number of rounds text
		int randomnum;  //random number generated by program
		int max;  //maximum of all random numbers
		int min;  //minimum of all random numbers

		System.out.print("Please enter the maximum random number to be used:");
		randmaxString = stdIn.nextLine();
		randmax = Integer.parseInt(randmaxString);
		max = 0;  //max initialized to zero as calculated max will always be higher
		min = randmax;  //min initialized to highest random number as min will always be lower
		double total = 0;  //double total of all random numbers selected
		double average = 0;  //double average of all random numbers selected

		System.out.print("Please enter the maximum number of rounds:");
		roundsString = stdIn.nextLine();
		rounds = Integer.parseInt(roundsString);

		System.out.printf(HEADING_FMT_STR, "Round", "Rand #", "Curr Max", "Curr Min", "Curr Total", "Curr Avg");

		for (int i = rounds; i > 0; i--)  //perform loop i times, where i is user entered number of rounds
		{
			randomnum = random.nextInt(randmax + 1);
			max = Math.max(max, randomnum);  //calculated max
			min = Math.min(min, randomnum);  //calculated min
			total += randomnum;  //calculated total
			average = total / (1 + rounds - i);  //calculated average
			System.out.printf(DATA_FMT_STR, (1 + rounds - i), randomnum, max, min, total, average);
		}  //end for

		System.out.print("End Run...");
	}  //end main
}  //end class